/**
 * Created by pingfengafei on 3/8/17.
 */

export const mapFraudSignalKeyToDisplayName = {
  'proxyIP': '代理检测',
  'idcIP': '消息是否来源于IDC机房',
  'cracked': 'Root检测',
  'uaMismatch': 'UA不匹配检测',
  'maxentID.1m': '相同Maxent ID 1分钟内的',
  'maxentID.5m': '相同Maxent ID 5分钟内的',
  'maxentID.15m': '相同Maxent ID 15分钟内的',
  'maxentID.1h': '相同Maxent ID 1小时内的',
  'maxentID.6h': '相同Maxent ID 6小时内的',
  'maxentID.1d': '相同Maxent ID 1天内的',
  'maxentID.7d': '相同Maxent ID 7天内的',
  'did.1m': '相同设备ID 1分钟内的',
  'did.5m': '相同设备ID 5分钟内的',
  'did.15m': '相同设备ID 15分钟内的',
  'did.1h': '相同设备ID 1小时内的',
  'did.6h': '相同设备ID 6小时内的',
  'did.1d': '相同设备ID 1天内的',
  'did.7d': '相同设备ID 7天内的',
  'ipGeo.1m': '相同城市1分钟内的',
  'ipGeo.5m': '相同城市5分钟内的',
  'ipGeo.15m': '相同城市15分钟内的',
  'ipGeo.1h': '相同城市1小时内的',
  'ipGeo.6h': '相同城市6小时内的',
  'ipGeo.1d': '相同城市1天内的',
  'ipGeo.7d': '相同城市7天内的',
  'ipSeg24.1m': '相同IP C段1分钟内的',
  'ipSeg24.5m': '相同IP C段5分钟内的',
  'ipSeg24.15m': '相同IP C段15分钟内的',
  'ipSeg24.1h': '相同IP C段1小时内的',
  'ipSeg24.6h': '相同IP C段6小时内的',
  'ipSeg24.1d': '相同IP C段1天内的',
  'ipSeg24.7d': '相同IP C段7天内的',
  'refereeID.1m': '相同推荐人账号ID 1分钟内的',
  'refereeID.5m': '相同推荐人账号ID 5分钟内的',
  'refereeID.15m': '相同推荐人账号ID 15分钟内的',
  'refereeID.1h': '相同推荐人账号ID 1小时内的',
  'refereeID.6h': '相同推荐人账号ID 6小时内的',
  'refereeID.1d': '相同推荐人账号ID 1天内的',
  'refereeID.7d': '相同推荐人账号ID 7天内的',
  'shopID.1m': '相同商户账户ID 1分钟内的',
  'shopID.5m': '相同商户账户ID 5分钟内的',
  'shopID.15m': '相同商户账户ID 15分钟内的',
  'shopID.1h': '相同商户账户ID 1小时内的',
  'shopID.6h': '相同商户账户ID 6小时内的',
  'shopID.1d': '相同商户账户ID 1天内的',
  'shopID.7d': '相同商户账户ID 7天内的',
  'bankAccNum.1m': '相同银行卡号1分钟内的',
  'bankAccNum.5m': '相同银行卡号5分钟内的',
  'bankAccNum.15m': '相同银行卡号15分钟内的',
  'bankAccNum.1h': '相同银行卡号1小时内的',
  'bankAccNum.6h': '相同银行卡号6小时内的',
  'bankAccNum.1d': '相同银行卡号1天内的',
  'bankAccNum.7d': '相同银行卡号7天内的',
  'shippingAddress.1m': '相同收货地址1分钟内的',
  'shippingAddress.5m': '相同收货地址5分钟内的',
  'shippingAddress.15m': '相同收货地址15分钟内的',
  'shippingAddress.1h': '相同收货地址1小时内的',
  'shippingAddress.6h': '相同收货地址6小时内的',
  'shippingAddress.1d': '相同收货地址1天内的',
  'shippingAddress.7d': '相同收货地址7天内的',
  'mobileNum.1m': '相同电话号码1分钟内的',
  'mobileNum.5m': '相同电话号码5分钟内的',
  'mobileNum.15m': '相同电话号码15分钟内的',
  'mobileNum.1h': '相同电话号码1小时内的',
  'mobileNum.6h': '相同电话号码6小时内的',
  'mobileNum.1d': '相同电话号码1天内的',
  'mobileNum.7d': '相同电话号码7天内的'
};